version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vitavet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  db_data:
