version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vitavet
    ports: ["5432:5432"]
    volumes: [db:/var/lib/postgresql/data]
volumes: { db: {} }
