[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "if [ \"$SERVICE_TARGET\" = \"api\" ]; then pnpm --filter api build; fi",
  "if [ \"$SERVICE_TARGET\" = \"web\" ]; then pnpm --filter web build; fi"
]

[start]
cmd = "bash -lc 'if [ \"$SERVICE_TARGET\" = \"api\" ]; then pnpm --filter api start:prod; else pnpm --filter web preview --host 0.0.0.0 --port 3000; fi'"
