[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm --filter api build",
  "pnpm --filter web build"
]

[start]
cmd = "pnpm --filter api start:prod"
