[build]
builder = "nixpacks"

[deploy]
startCommand = "pnpm preview --host 0.0.0.0 --port 3000"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"
