name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - name: Install dependencies
        run: pnpm install

      - name: Run API tests
        run: pnpm --filter api test

      - name: Run Web tests
        run: pnpm --filter web test:run

      - name: Run API e2e tests
        run: pnpm --filter api test:e2e

      - name: Lint API
        run: pnpm --filter api lint

      - name: Lint Web
        run: pnpm --filter web lint

      - name: Build API
        run: pnpm --filter api build

      - name: Build Web
        run: pnpm --filter web build
